site_name: LinuxProfile
site_url: http://linuxprofile.com
repo_url: https://github.com/MyLinuxProfile/linux-profile

nav:
    - Home: index.md
    - Installation: nav/installation.md
    - Commands:
        - Config:
            - nav/commands/config/index.md
            - nav/commands/config/exemple.md
        - Add:
            - nav/commands/add/index.md
            - nav/commands/add/exemple.md
        - Remove:
            - nav/commands/remove/index.md
            # - nav/commands/remove/exemple.md
        - Install:
            - nav/commands/install/index.md
            # - nav/commands/install/exemple.md
        - Uninstall:
            - nav/commands/uninstall/index.md
            # - nav/commands/uninstall/exemple.md
        - List:
            - nav/commands/list/index.md
            # - nav/commands/list/exemple.md
    - Storage: nav/storage.md
    - Backup: nav/backup.md

theme: 
    name: material
    logo: assets/linux-profile-icon.png
    favicon: assets/linux-profile-icon.ico

extra_css:
  - stylesheets/extra.css
